#!/usr/bin/env bash
#ALWAYS SAME INITIALIZATION 
set -e

if ! [ -x "$(command -v publishtools)" ]; then
  builld
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
    brew services start redis
else
    sudo /etc/init.d/redis-server start
fi
   
