#!/usr/bin/env bash
set -ex
if [[ -z "${DIR_CT}" ]]; then 
    echo 'Make sure to source /workspace/env before calling this script.'
    exit 1
fi
source $DIR_CT/scripts/ct_init

v_check

#CHECK IF DIR EXISTS, IF NOT CLONE
if ! [[ -f "$HOME/.vmodules/done_crystallib" ]]; then
    sudo rm -rf ~/.vmodules/despiegk/
    mkdir -p ~/.vmodules/despiegk/    

    v install despiegk.crystallib
    v install patrickpissurno.redis
    v install despiegk.crystallib
    v install nedpals.vex

    if ! [[ "$PBRANCH" == "development" ]]; then
        echo " - THERE IS BRANCH FOR CRYSTAL LIB"
        pushd ~/.vmodules/despiegk/crystallib
        git fetch origin $PBRANCH:$PBRANCH
		git checkout $PBRANCH
        popd
    fi

    touch "$HOME/.vmodules/done_crystallib"
fi


