#!/usr/bin/env bash
#ALWAYS SAME INITIALIZATION 
set -e
if [[ -z "${DIR_CT}" ]]; then 
    echo 'DIR_CT needs to be set'
    exit 1
else
    pushd $DIR_CT/scripts
    source ct_init
    popd "$@" > /dev/null
fi

sudo rm -f /usr/local/bin/crystaltools
sudo rm -f /opt/homebrew/bin/crystaltools
sudo rm -f /usr/local/bin/publishtools
sudo rm -f /opt/homebrew/bin/publishtools

#get the crystal libs
cl_build

git_get github.com/crystaluniverse crystaltools
pushd $CDIR/crystaltools

# v -gc boehm -prod crystaltools.v
if [[ "$OSTYPE" == "darwin"* ]]; then
    # v -d static_boehm  -gc boehm -prod crystaltools.v
    v -d net_blocking_sockets -d static_boehm  -gc boehm crystaltools.v
else
    v -d static_boehm  -gc boehm -cflags -static -prod crystaltools.v
fi


# v -d static_boehm  -gc boehm crystaltools.v

#v  crystaltools.v
   
if [[ "$OSTYPE" == "darwin"* ]]; then
    if [[ `uname -m` == 'arm64' ]]; then
        sudo cp ct /opt/homebrew/bin/crystaltools
        chmod 770 /opt/homebrew/bin/crystaltools
        #to prepare for upload to our releases
        cp crystaltools ~/Downloads/crystaltools_osx_arm
    else        
        sudo cp ct /usr/local/bin/crystaltools
        chmod 770 /usr/local/bin/crystaltools    
        #to prepare for upload to our releases
        cp crystaltools ~/Downloads/crystaltools_osx
    fi
else
    #for linux
    sudo crystaltools crystaltools /usr/local/bin/crystaltools
    chmod 770 /usr/local/bin/crystaltools    
fi

popd "$@" > /dev/null

echo " - crystaltools build ok"