#!/usr/bin/env bash

if ! [ -x "$(command -v crystaltools)" ]; then
  ct_build
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
    brew services start redis
else
    sudo /etc/init.d/redis-server start
fi
   


