#!/usr/bin/env bash
#ALWAYS SAME INITIALIZATION 
set -ex
if [[ -z "${DIR_CT}" ]]; then 
    echo 'Make sure to source /workspace/env before calling this script.'
    exit 1
fi
source $DIR_CT/scripts/ct_init

if [[ "$OSTYPE" == "linux-gnu"* ]]; then 

    sudo rm -f /usr/local/bin/publishtools
    sudo bash -c 'curl -L https://github.com/freeflowuniverse/crystaltools/releases/download/first/publishtools_linux > /usr/local/bin/publishtools'
    sudo chmod +x /usr/local/bin/publishtools

    sudo /etc/init.d/redis-server start

elif [[ "$OSTYPE" == "darwin"* ]]; then

    if ! [ -x "$(command -v mc)" ]; then
        brew install mc
        brew install openssl
    fi

    if ! [ -x "$(command -v redis-server)" ]; then
        brew install redis
    fi

    brew services start redis
    
    if [[ `uname -m` == 'arm64' ]]; then
        sudo rm -f /usr/local/bin/publishtools
        # https://github.com/freeflowuniverse/crystaltools/releases/download/first/publishtools_osx_arm
        curl -L https://github.com/freeflowuniverse/crystaltools/releases/download/first/publishtools_osx_arm > /opt/homebrew/bin/publishtools
        chmod 770 /opt/homebrew/bin/publishtools
    else
        rm -f /opt/homebrew/bin/publishtools
        curl -L https://github.com/freeflowuniverse/crystaltools/releases/download/first/publishtools_osx> /usr/local/bin/publishtools
        chmod 770 /usr/local/bin/publishtools
    fi
fi



echo " - INSTALL DONE"


