#!/usr/bin/env bash
#ALWAYS SAME INITIALIZATION 
set -e

sudo rm -rf $DIR_CODE/v
sudo rm -rf $DIR_CODE/vls
sudo rm -rf $DIR_CODE_INT/v
sudo rm -rf $DIR_CODE_INT/vls
sudo rm -rf $HOME/.vmodules
sudo rm -f "$HOME/.vmodules/done_crystallib"
sudo rm -rf /usr/local/bin/vls
sudo rm -rf /usr/local/bin/v
sudo rm -rf /usr/local/bin/ct
sudo rm -rf /usr/local/bin/crystaltools
sudo rm -rf /usr/bin/v

sudo rm -rf ~/.vmodules

sudo rm -rf ~/_code

set +ex

sudo chown -R ${USER}:staff /usr/local/bin
sudo chown -R ${USER}:staff ~/Downloads
sudo chown -R ${USER}:staff /opt/homebrew/bin

mkdir -p $DIR_CODE

