#!/usr/bin/env bash
#ALWAYS SAME INITIALIZATION 
set -e
if [[ -z "${DIR_CT}" ]]; then 
    echo 'DIR_CT needs to be set'
    exit 1
else
    pushd $DIR_CT/scripts
    source ct_init
    popd "$@" > /dev/null
fi

sudo rm -rf $DIR_CODE/v
sudo rm -rf $DIR_CODE/vls
sudo rm -rf $DIR_CODE_INT/v
sudo rm -rf $DIR_CODE_INT/vls
sudo rm -rf $HOME/.vmodules
sudo rm -rf $DIR_CODE/crystallib
sudo rm -rf /usr/local/bin/vls
sudo rm -rf /usr/local/bin/v
sudo rm -rf /usr/local/bin/ct
sudo rm -rf /usr/local/bin/crystaltools

sudo rm -rf ~/.vmodules