#!/usr/bin/env bash
#ALWAYS SAME INITIALIZATION 
set -e
if [[ -z "${DIR_CT}" ]]; then 
    echo 'Make sure to source /workspace/env before calling this script.'
    exit 1
fi
source $DIR_CT/scripts/ct_init

v up
v upgrade

pushd ~/.vmodules/despiegk/crystallib
git pull
popd "$@" > /dev/null

pushd $DIR_CT
git pull
popd "$@" > /dev/null

build

echo " - upgrade ok"