#!/bin/bash

set -e

source $DIR_CT/scripts/ct_init
#WHY DO WE HAVE THIS?
if [[ -d "/workspace" ]]; then
sudo chown gitpod:gitpod -R /tmp
fi

echo " - INSTALL NVM"

mkdir -p $DIR_BASE
rm -f $DIR_BASE/nvm.sh
curl -s -o $DIR_BASE/nvm.sh https://raw.githubusercontent.com/nvm-sh/nvm/master/nvm.sh
export NVM_DIR=$DIR_BASE
source $DIR_BASE/nvm.sh

echo " - INSTALL NODEJS"
nvm install --lts
node -v
npm install --global yarn
npm install pm2 -g    

echo " - INSTALL GRIDSOME"
npm install --global @gridsome/cli

echo " - GET THREEFOLD DATA"
git_get github.com/threefoldfoundation threefold_data



 
