#!/bin/bash

set -e

# export PATH=$base/bin:$PATH

source $DIR_BASE/nvm.sh

nvm use --lts

if ! [ -x "$(command -v node)" ]; then
    web_install
fi

if [[ -f "gridsome.server.js" ]]; then
    echo "website found"
else
    echo "ERROR: could not find threefold web (gridsome enabled) directory, make sure you run this command from a web directory."
    exit 1
fi





# if [ -f vue.config.js ]; then
# npm run-script serve
# else
# gridsome develop
# fi

rm -f yarn.lock
rm -rf .cache

npm install
npm install --global @gridsome/cli

rm -f content/blog
ln -s  /workspace/code/threefold_data/content/blog content/blog
rm -f content/news
ln -s  /workspace/code/threefold_data/content/news content/news
rm -f content/person
ln -s  /workspace/code/threefold_data/content/person content/person
rm -f content/project
ln -s  /workspace/code/threefold_data/content/project content/project

