#!/bin/bash

set -e

# export PATH=$base/bin:$PATH

source $DIR_BASE/nvm.sh

nvm use --lts


if [ -d node_modules ]; then
echo "node modules exists"
else
website_install
fi


if [ -f vue.config.js ]; then
npm run-script serve
else
gridsome develop
fi





